# External plugins
plugins:
  - jekyll-sitemap
  - jekyll-paginate

exclude:
  - "/vendor/"

# Site settings
title: Modern IT Blog
subtitle: Thoughts and useful stuff on my journey to being entirely in the cloud.
name: Scott Pettit
description: Thoughts and useful stuff on my journey to being entirely in the cloud.
# Base URL of site (i.e. /blog). It should always start with a slash,
# and never end with a slash. Set it to a blank value if hosting at the
# root of your server.
baseurl: ""
url: "https://scottpettit.nz" # the base hostname & protocol for your site
# TODO: Get a cover image and logo created
cover: 
logo:

# Build settings
markdown: kramdown
inter_post_navigation: false
highlightjs_theme: "monokai-sublime"

# Pagination Settings
# https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-GENERATOR.md#site-configuration
#pagination:
#  enabled: true
#  per_page: 2
paginate: 5
# Google analytics
# ga_tracking_id: "UA-XXXX-1"

# Social icons and sharing options
#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
#
# Example:
#
# social:
#   - name: Twitter                         # Name of the service
#     icon: twitter                         # Font Awesome icon to use (minus fa- prefix)
#     username: "@TheBenCentra"             # (User) Name to display in the footer link
#     url: https://twitter.com/TheBenCentra # URL of your profile (leave blank to not display in footer)
#     desc: Follow me on Twitter            # Description to display as link title, etc
#     share: true                           # Include in the "Share" section of posts
social:
  - name: Twitter
    icon: twitter
    username: smpettit
    url: https://twitter.com/smpettit
    desc: Follow me on Twitter
    share: true

  - name: LinkedIn
    icon: linkedin
    username: Scott Pettit
    url: https://www.linkedin.com/in/scottpettit/
    desc: Connect with me on LinkedIn
    share: true

# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
    fb_image: "/assets/logo.png"
    fb_image_width: 612
    fb_image_height: 605
    fb_image_type: "image/png"

    twitter_image: "/assets/logo.png"